---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: doma-mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "managed-nfs-storage"

