apiVersion: apps/v1
kind: Deployment
metadata:
  name: doma-mariadb
spec:
  selector:
    matchLabels:
      app: doma-mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: doma-mariadb
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: doma-mariadb
      containers:
      - name: mariadb
        imagePullPolicy: Always
        image: nwik/doma-mariadb:10.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "nwik"
        - name: MYSQL_DATABASE
          value: "doma"
        - name: MYSQL_USER
          value: "nwik"
        - name: MYSQL_PASSWORD
          value: "nwik"
        volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
        ports:
        - name: db
          containerPort: 3126

