apiVersion: v1
kind: PersistentVolume
metadata:
  name: doma-mariadb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/array1/kube_nfs/doma_mariadb
    server: 192.168.1.209
    readOnly: false

