---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rook-mariadb-pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

