---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: doma-mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: doma-mariadb-pv

