apiVersion: v1
kind: PersistentVolume
metadata:
  name: doma-web
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "microsoft.com/smb"
    secretRef:
      name: smbcreds
    options:
      source: "//192.168.1.209/kube_nfs/doma_web"
      mountoptions: "vers=1.0,guest,rw,suid,dev,exec,auto,users,async,atime,_netdev,uid=999"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: doma-web-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: doma-web

