---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: doma-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "managed-nfs-storage"

