apiVersion: v1
data:
  config.yaml: |
    crds:
    - group: monitoring.coreos.com
      version: v1
      kind: Prometheus
    - group: monitoring.coreos.com
      version: v1
      kind: Alertmanager
    - group: certmanager.k8s.io 
      version: v1alpha1
      kind: Certificate
kind: ConfigMap
metadata:
  name: gitops-operator-config
