apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: niklasw-iki-fi
  namespace: default
spec:
  secretName: niklasw-iki-fi-tls
  email: "niklas.wik@iki.fi"
  issuerRef:
    name: letsencrypt-prod
  commonName: niklasw.iki.fi
  dnsNames:
  - niklasw.iki.fi
  - www.niklasw.iki.fi
  acme:
    config:
    - http01:
        ingress: weather
      domains:
      - niklasw.iki.fi
      - www.niklasw.iki.fi
