apiVersion: v1
kind: Service
metadata:
  name: weather
  namespace: default
spec:
  ports:
  - name: https
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: weather
  type: ClusterIP


