apiVersion: v1
kind: Service
metadata:
  labels:
    app: haproxy-prom-metrics
  name: haproxy-prom-metrics
  namespace: ingress-controller
spec:
  ports:
  - name: prom-metrics
    port: 9101
    targetPort: prom-metrics
  selector:
    run: haproxy-ingress
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxy
  namespace: monitoring
  labels:
    app: haproxy-prom-metrics
    k8s-app: haproxy-metrics
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: haproxy-prom-metrics
  namespaceSelector:
    matchNames:
    - ingress-controller
  endpoints:
  - port: prom-metrics
    interval: 30s
    path: /metrics
