apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb-svc
  namespace: default
spec:
  ports:
  - name: api
    port: 8086
    protocol: TCP
    targetPort: 8086
  - name: graphite
    port: 2003
    protocol: TCP
    targetPort: 2003
  - name: collectd
    port: 25826
    protocol: TCP
    targetPort: 25826
  - name: udp
    port: 8089
    protocol: TCP
    targetPort: 8089
  - name: opentsdb
    port: 4242
    protocol: TCP
    targetPort: 4242
  - name: backup-restore
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: influxdb
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.1.3

