apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: influxdb
      influxdb_cr: influxdb
  serviceName: influxdb-svc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: influxdb
        influxdb_cr: influxdb
      namespace: default
    spec:
      containers:
      - image: influxdb:1.6.3-alpine
        imagePullPolicy: Always
        name: influxdb
        resources:
          limits:
            cpu: "8"
            memory: 16Gi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/influxdb/influxdb.conf
          name: influxdb-config
          subPath: influxdb.conf
        - mountPath: /var/lib/influxdb/
          name: influxdb-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: influxdb-config
        name: influxdb-config
      - name: influxdb-data
        flexVolume:
          driver: "microsoft.com/smb"
          secretRef:
            name: smbcreds
          options:
            source: "//192.168.1.209/kube_nfs/influxdb"
            mountoptions: "vers=1.0"
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: influxdb-66869b5b84
  observedGeneration: 1
  replicas: 1
  updateRevision: influxdb-66869b5b84
  updatedReplicas: 1
